// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ImageProcessing")>]
[<assembly: AssemblyProductAttribute("ImageProcessing")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-12-19T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","69b0a7031c7867757fe29fa2d1117f346920fc9e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ImageProcessing"
    let [<Literal>] AssemblyProduct = "ImageProcessing"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-12-19T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "69b0a7031c7867757fe29fa2d1117f346920fc9e"
